FreeTeleportRange: 150
CostPerBlock: 1.00
InterdimensionalTravelCost: 500
MaximumWaypoints: 256
EnvironmentEffects: true
AutoSave: true
UseVault: false
MakeGlobalCost: 100

WaypointTeleportTime: 0
WarpscrollTeleportTime: 5

WaystoneRecipe:
  Top: ' S '
  Middle: 'SNS'
  Bottom: ' S '
  Materials:
    S: SHULKER_SHELL
    N: NETHER_STAR

Warpscroll:
  Enabled: true
  Cooldown: 600
  XPMultiplier: 1.0
  RemoveAfterUse: false
  Recipe:
    Top: ' P '
    Middle: 'PSP'
    Bottom: ' P '
    Materials:
      S: SHULKER_SHELL
      P: PAPER